# Generated by Django 5.0.4 on 2024-04-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discrpition', models.TextField()),
                ('devoloper', models.CharField(max_length=255)),
                ('date_of_issue', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
